version: '3.8'

services:
  app:
    build: .
    ports:
      - "3005:3005"
      - "8087:8087"
    environment:
      - DB_HOST=31.97.177.87
      - DB_PORT=3307
      - DB_USER=root
      - DB_PASSWORD=StrongPass123
      - DB_NAME=employe
      - JWT_SECRET=change-this-secret-key
      - NODE_ENV=production
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
